name: lockerroomtalk
description: "Locker Room Talk is a modern dating review platform where people share honest experiences and build meaningful connections."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  
  # Google Sign-In
  google_sign_in: ^6.2.2
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # Location
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^3.2.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  
  # HTTP & AI
  http: ^1.2.2
  
  # Chat & Real-time
  flutter_chat_ui: ^1.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
