// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdGoo6Z2uHXNmFyXnKdltwrMUXPcp_4A',
    appId: '1:514288923681:web:aa8d8134086ec33ebc5f60',
    messagingSenderId: '514288923681',
    projectId: 'locker-room-talk-app',
    authDomain: 'locker-room-talk-app.firebaseapp.com',
    storageBucket: 'locker-room-talk-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS1MKSCCtlWsTin0jR5GoVLhb1k_GhbGI',
    appId: '1:514288923681:android:fb311785def737eebc5f60',
    messagingSenderId: '514288923681',
    projectId: 'locker-room-talk-app',
    storageBucket: 'locker-room-talk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTRnA77TYAbuyBbAYUYiAAAhVVEYBrk4',
    appId: '1:514288923681:ios:3692234b116ce89abc5f60',
    messagingSenderId: '514288923681',
    projectId: 'locker-room-talk-app',
    storageBucket: 'locker-room-talk-app.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoMacOSKeyForLockerRoomTalk',
    appId: '1:123456789012:macos:demo123456789',
    messagingSenderId: '123456789012',
    projectId: 'lockerroomtalk-demo',
    storageBucket: 'lockerroomtalk-demo.appspot.com',
    iosBundleId: 'com.example.lockerroomtalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoWindowsKeyForLockerRoomTalk',
    appId: '1:123456789012:web:demo123456789windows',
    messagingSenderId: '123456789012',
    projectId: 'lockerroomtalk-demo',
    authDomain: 'lockerroomtalk-demo.firebaseapp.com',
    storageBucket: 'lockerroomtalk-demo.appspot.com',
    measurementId: 'G-DEMO123456WIN',
  );
}